logging:
  config: "classpath:logback-spring.xml"
  level:
    root: info
spring:
  application:
    name: cap-source

app:
  vertx:
    event-loop-pool-size: 8
  registry:
    host: localhost
    port: 7000
    tcp_server_thread_pool: 4

source:
  binance:
    buffer-size: 1024
    symbols: btcusdt,ethusdt

